services:
  redis:
    image: redis:alpine
    container_name: sre-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  api-service:
    build:
      context: .
      target: api-service
    container_name: sre-api
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - GIN_MODE=debug # Good for local dev visibility
      - REDIS_ADDR=redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    depends_on:
      - redis # Though strict dependency isn't required for API, it's good practice for the stack
      - jaeger

  worker-service:
    build:
      context: .
      target: worker-service
    container_name: sre-worker
    ports:
      - "8081:8081"
    environment:
      - WORKER_PORT=8081
      - REDIS_ADDR=redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    depends_on:
      redis:
        condition: service_healthy
      jaeger:
        condition: service_started

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: sre-jaeger
    ports:
      - "16686:16686" # UI
      - "4318:4318" # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
