apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    {{- include "sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sre-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "sre-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      # Spot VMs disabled - GCP quota limits on free tier
      # nodeSelector:
      #   cloud.google.com/gke-spot: "true"
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.worker.containerSecurityContext | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 8081
              protocol: TCP
          env:
            - name: WORKER_PORT
              value: "8081"
            - name: REDIS_ADDR
              value: "{{ .Release.Name }}-redis:6379"
          livenessProbe:
            {{- toYaml .Values.worker.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
